urls = [
# "http://2678.appygen.net",
# "http://44801.appygen.net",
# "http://4rstudio.com",
# "http://a2zwallpaper.sagarzone.com",
# "http://ababar.com",
# "http://abirochas.com.br",
# "http://ackmi.com",
# "http://andyherbert.net",
# "http://appdevtechnolabs.com/",
# "http://ArabRoid.SelloHost.com",
# "http://babyangelgames.in/",
# "http://bestfreeapps4u.com/",
# "http://bhimaapps.blogspot.com/",
# "http://birthday.arvindkatoch.com/",
# "http://bit.ly/cemilanDev",
# "http://bittyapps.in",
# "http://crespi.berdetak.com/privacy_policy",
# "http://CrochetDesigns.com",
# "http://decorunhas.com",
# "http://dev3pro.com/",
# "http://dkmtechnologies.in",
# "http://drawapp.cc/",
# "http://dress30.com/",
# "http://duoapptech.com",
# "http://etakbeer.com/",
# "http://faheel.store/",
# "http://fatstudio.club",
# "http://furthergrow.com/",
# "http://hk1a1a.com/",
# "http://ihappsprivacypolicy.blogspot.com/",
# "http://imha.wo.to",
# "http://indpgroups.ezyro.com",
# "http://ionicbucket.com/",
# "http://istanbulbilsem.meb.k12.tr",
# "http://italobarbiero.com",
# "http://kefooi.com",
# "http://kidslearninggame.in/",
# "http://littletreeapps.website",
# "http://lovelogos4u.com",
# "http://madseven.co/",
# "http://marclee.io",
# "http://marclee.io/en/friends/",
# "http://marclee.io/en/more-and-less/",
# "http://marshallfredericks.org",
# "http://maxproapp.us/",
# "http://mjcreativeworks.in",
# "http://moayada.com",
# "http://musmon.com",
# "http://nokuteku.site/",
# "http://pakettiga.xyz/arev/BabyHat/app-ads.txt",
# "http://pakettiga.xyz/arev/BeautifulBirdsWallpaper/app-ads.txt",
# "http://pakettiga.xyz/arev/BottlePaintingArts/app-ads.txt",
# "http://pakettiga.xyz/arev/RockingChairDesigns/app-ads.txt",
# "http://pakettiga.xyz/arev/WomenCardigan/app-ads.txt",
# "http://pakettiga.xyz/arev/WomenNightDress/app-ads.txt",
# "http://paulabenavides.cenart.gob.mx",
# "http://planetsstudio.club",
# "http://postinsta.in/",
# "http://qsl.net/iz4cco",
# "http://sense-immaterialreality.com/",
# "http://shoutrlabs.com",
# "http://thewiedmannbible.com",
# "http://tuhocandroid.com/",
# "http://webskysolutions.com/contact-us/",
# "http://witchad.com",
# "http://www.3dinteractive.se",
# "http://www.anisnajib.co.nr",
# "http://www.artedigital.com.mx",
# "http://www.bam.fyi",
# "http://www.c-launcher.com/",
# "http://www.carrioncastillo.com",
# "http://www.culturespaces.com",
# "http://www.cytau.com/",
# "http://www.digitalcairo.com",
# "http://WWW.DOMENICOIRASINO.COM",
# "http://www.dsgn.foundation",
# "http://www.ecard.co.ke",
# "http://www.edinkira.com",
# "http://www.eridanus.info",
# "http://www.feureau.com",
# "http://www.fida.pk",
# "http://www.friendsadvertising.com",
# "http://www.gkegg.com/",
# "http://www.gooldari.com",
# "http://www.jiki.si",
# "http://www.jjrobots.com",
# "http://www.mac-lyon.com/mac/",
# "http://www.mitz.pk/",
# "http://www.mlksoft.net",
# "http://www.NujoSystems.com",
# "http://www.pixelforce.in",
# "http://www.planethit.info",
# # "http://www.prabudroid.com/",
# "http://www.pragmainfotech.com",
# "http://www.programasdecomputo.com",
# "http://www.sergebouchardon.com/",
# "http://www.shreeumapolymers.com",
# "http://www.sitinoldae.com",
# "http://www.smoothhq.com",
# "http://www.sotec.es",
# "http://www.sweefitstudios.com/",
# "http://www.swibeat.com/WebYoutube/index.php?lang=EN&ltype=L&smid=",
# "http://www.vacationcountdownstorymaker.com",
# "http://www.wienelware.nl",
# "http://www.yannickgueguen.com",
# "http://www.yuliyalanina.com/",
# "http://www12.plala.or.jp/Beethoven/whitefawn.html",
# "https://15858.appads-txt.com/ads-app.txt",
# "https://727.appads-txt.com",
# "https://8912.appads-txt.com/",
# "https://8975.appads-txt.com/",
# "https://9680.appads-txt.com",
# "https://a6ca82b28.app-ads-txt.com/",
# "https://adsflast.blogspot.com/",
# "https://adver.maxeomsoft.com/",
# "https://alledotech.in",
# "https://amatller.org",
# "https://ant-app.com/",
# "https://app.draw4all.co.uk/app-website/",
# "https://app.shaggyowl.com/?ccs=menuLogoFront2018",
# "https://app11784899.appsgeyser.com/app-ads.txt",
# "https://app12691833.appsgeyser.com/",
# "https://app13564980.appsgeyser.com/",
# "https://apper.apperalinstante.com/descargasuperapps1",
# "https://appzawi.appzinfo.com/",
# "https://aray34publishing.blogspot.com/ads.txt",
# "https://arcuilo.com/pixart/",
# "https://ardeveloperss.blogspot.com",
# "https://artartstudio.blogspot.com",
# "https://artbacknt.com.au/show/balnhdhurr-a-lasting-impression/",
# "https://artopencalls.blogspot.com",
# "https://aulaul-app-dev.flycricket.io/",
# "https://bakasdo.flycricket.io/",
# "https://bakasdo.flycricket.io/privacy.html",
# "https://bce1d3da0.app-ads-txt.com",
# "https://bd69d0f38.app-ads-txt.com",
# "https://bestdiylists.com/",
# "https://bestleafblowercordless.com/",
# "https://bibitown.com/",
# "https://blog.naver.com/dpfslsyfkslsi",
# "https://brandflex.in",
# "https://brandoapp.com/",
# "https://brandyappsdeveloper2021.blogspot.com/",
# "https://buildingprint.site/",
# "https://bunnysweet-app.web.app",
# "https://c779d321c.app-ads-txt.com",
# "https://carmelitans.org/",
# "https://ccbe8c31.app-ads-txt.com/",
# "https://ccfd81386.app-ads-txt.com",
# "https://colorgo-games.blogspot.com",
# "https://coloringbookappplay.blogspot.com",
# "https://coloringforall.herokuapp.com/",
"https://creativedotweb.com/",
"https://czapski.art.pl/",
"https://dafoudilstore.blogspot.com/",
"https://dailyshare.in/",
"https://depuz.pk",
"https://devtakbiran.blogspot.com",
"https://docs.google.com/document/d/10Bqe3LI8Q6xZNWSa2vEliOcTPI9JM3yGbYzSKfD018o/edit?usp=sharing",
"https://docs.google.com/document/d/1ARoEBoAjW1CkZyvsrSjWrRlCJfSlE9xspf9DjXNE2mQ/edit?usp=sharing",
"https://docs.google.com/document/d/1AXGVBDzKOHJb6LCtYy-vs9CJtOH8h3lFlAiEdBT-Yo8/edit?usp=sharing",
"https://docs.google.com/document/d/1B-HaH464alVztXaxlua3vgVqxcYgQDbY_sD9VnIeRQo/edit?usp=sharing",
"https://docs.google.com/document/d/1cBJ6AeZ-AUYaQupmdzkIDuRvUAS6hjzz1E-dyV9gGLo/edit?usp=sharing",
"https://docs.google.com/document/d/1ga879G-IdIiXkntK4MGcxBgyntULtdf1q3rSc7jShhA/edit?usp=sharing",
"https://docs.google.com/document/d/1hnQJ0K13iH43KnvesIM42D1x3paUUL2qUfEdqguwpTY/edit?usp=sharing",
"https://docs.google.com/document/d/1rzqU0J9dO7sxbOBFpXxHW0zewbzIraRkORVJlHWJ5Fg/edit?usp=sharing",
"https://docs.google.com/document/d/1t3TYM4tnMNoyV6l7GH0jzCeMZy2eFhFUMZA3QfKrVM0/edit?usp=sharing",
"https://docs.google.com/document/d/1wjMBEC_8OyIGQgDM6Ts3HDTbBVA0999D5BfzL7kulHw/edit?usp=sharing",
"https://docs.google.com/document/d/1z_oFAzZC1nWufUjyjbG5Bi01MhisC0j2uvDSIHR-AJ8/edit?usp=sharing",
"https://docs.google.com/document/d/1zl_EyN2YccqW2S3yGL9zNx8i3ji0ZOpC8UR3nyD-zkg/edit?usp=sharing",
"https://dom35.by/",
"https://drawingdragon.ribarapps.com/",
"https://drawingfoodanddrinks.ribarapps.com/",
"https://drawinggame.ribarapps.com/",
"https://drivewallpapergodev.blogspot.com/",
"https://eba71b0fc.app-ads-txt.com/",
"https://ecomuseoac.org/",
"https://f60de654b.app-ads-txt.com",
"https://fida.pk",
"https://flydiz.com/",
"https://foxdistroshop.com",
"https://gamesofficialguide.com/",
"https://genericappsco.web.app/",
"https://getinitx.com/en/",
"https://girisoft.com",
"https://github.com/nsiva7",
"https://github.com/ShinChven/potg_meme/blob/master/readme.md",
"https://grosstil.by/",
"https://hackesta.org",
"https://hhassanapp.blogspot.com/app-ads.txt",
"https://hindi.invitations.link",
"https://hsoftway.clueinfotech.com/",
"https://iamabs2001.github.io",
"https://iddroidapps.blogspot.com",
"https://ikhani.blogspot.com",
"https://indowalladstxt.blogspot.com/",
"https://internet-test-a465f.web.app/",
"https://intuitivelabs.blogspot.com",
"https://iqbalfreeapps.blogspot.com/app-ads.txt",
"https://ishicreations.com/",
"https://jayadev77.blogspot.com/ads.txt",
"https://jorgemaxstudio.blogspot.com",
"https://jsnet-company.blogspot.com",
"https://kochena-c6a74.web.app/app-ads.txt",
"https://lc2a2e6fa.app-ads-txt.com",
"https://lgl09d82.app-adstxt.dev/app-ads.txt",
"https://littledragonblue-modelismo.blogspot.com",
"https://macaronitvme.blogspot.com/ads.txt",
"https://maniagame441.blogspot.com",
"https://maniagame441.blogspot.com/",
"https://markethqltd.com/",
"https://minote9pro1.blogspot.com/",
"https://mishreeapp.blogspot.com/",
"https://moappsinc.blogspot.com/",
"https://mobiappsfun.blogspot.com/",
"https://modestdevelopers47.blogspot.com",
"https://n720cfa57.app-ads-txt.com",
"https://n8ebc2a8d.app-ads-txt.com",
"https://nasnas-studio.flycricket.io/",
"https://naveenkumarapps.blogspot.com",
"https://nc653acb2.app-ads-txt.com/app-ads.txt",
"https://ndd9229dd.app-ads-txt.com",
"https://newmehndi1.blogspot.com",
"https://nextdesigngeneration.blogspot.com/ads.txt",
"https://nirmallabs.com",
"https://novtieapps.blogspot.com/",
"https://nulledsourcecode.com/",
"https://obe493854.app-ads-txt.com",
"https://objetivoweb.es/",
"https://orpheogroup.com/it/",
"https://patreon.com/mimicsilhouette/overview",
"https://pd223112d.app-ads-txt.com",
"https://picartphotostudio.blogspot.com",
"https://podcastboosting.com",
"https://racunduniaku.blogspot.com/",
"https://ramaramaart.blogspot.com",
"https://redmenote9.blogspot.com/",
"https://redmi10tlite1.blogspot.com/",
"https://reverent-varahamihira-36d857.netlify.app/",
"https://room-ch.ch/",
"https://rosamichael.com/rathgeber/",
"https://rqrappshelp.blogspot.com",
"https://rvpixel.com",
"https://s35df1e39.app-ads-txt.com",
"https://sandstorm.appdom.club",
"https://secalhar.com",
"https://setiyostudio.blogspot.com/",
"https://shitheki.com/",
"https://signal-stickers.com/",
"https://sites.google.com/site/johnamoorprivacypolicy/",
"https://sites.google.com/view/wily-apps/home",
"https://skysolapp.blogspot.com//ads.txt",
"https://softmaticzone.blogspot.com/",
"https://structsoft.net",
"https://stylishappworld.web.app/",
"https://stylishcooltext009.blogspot.com/",
"https://sukasemuago.blogspot.com/",
"https://szarvasimuzeum.hu/",
"https://thefullefectapps.blogspot.com/",
"https://thekingsoftpolicies.blogspot.com/",
"https://themeandlaunchers.blogspot.com",
"https://to-app1.firebaseapp.com/",
"https://touchofdreams.tk",
"https://turkazzi.blogspot.com/",
"https://udantastri.blogspot.com/ads.txt",
"https://uonegroup.id/",
"https://vastactive.github.io/caae/",
"https://vd5c1ec33.app-ads-txt.com/app-ads.txt",
"https://veparbranding.com",
"https://videovibeapps.web.app/",
"https://vidmediadownloader.com/",
"https://w1c065265.app-ads-txt.com",
"https://w7e36b56.app-ads-txt.com",
"https://wallpaperciamikzone.blogspot.com/",
"https://wastickersapps2020.blogspot.com/",
"https://wiyartodeveloper.blogspot.com/ads.txt",
"https://www.24print.by/",
"https://www.akanksharawat.com/",
"https://www.alimlearningapp.com/",
"https://www.alwanbyti.com",
"https://www.archtoolkit.com",
"https://www.art-wake-up.de",
"https://www.artspots.net/",
"https://www.Ask.Video",
"https://www.atm-plushome.com/",
"https://www.boomtownfair.co.uk",
"https://www.brandlyapp.in",
"https://www.colourwalls.com/",
"https://www.contentarcade.com",
"https://www.creatorscorp.in",
"https://www.culturespaces.com/",
"https://www.digitemb.com/",
"https://www.facebook.com/profile.php?id=100014851176212&__tn__=%2CdlC-R-R&eid=ARDx9PHjX0mDMj2T2czCAiZ_JJFSaYxsg8crRAuuzN_IbTEAigrzRhsqIv3X5Mk1KN0FqPPBaKWAwOhD&hc_ref=ARQhMGARzDvKntLSk57l4TWweem7Ibtf5usOQtx3xaXevACJqyrVCJxojgreUT6YIUM",
"https://www.fdrs.tech/",
"https://www.flyerdec.com/",
"https://www.fortecloth.com/",
"https://www.fourthedesign.gr",
"https://www.idcgames.com",
"https://www.instagram.com/RoxWatchDesign",
"https://www.kmfa.gov.tw/",
"https://www.kulhariweb.com/",
"https://www.modaile.com/",
"https://www.mvltrapps.com",
"https://www.navishaapp.eu.org/",
"https://www.netbinnacle.com/",
"https://www.olo-app.com/",
"https://www.pijhippie.com",
"https://www.saint-quentin.fr/109-musee-lecuyer.htm",
"https://www.silvforlife.de",
"https://www.skylabs.org",
"https://www.somtechweb.com/",
"https://www.techbymithilesh.com",
"https://www.teknapps.com/",
"https://www.telugumix.co.in",
"https://www.telugumix.co.in/",
"https://www.theulans.com",
"https://www.tukangstylebali.com/",
"https://www.vogelsang-furnier.com/",
"https://www.woehr.de",
"https://www.ybrdigital.in",
"https://y5fb4ed61.app-ads-txt.com",
"https://yadesign-godev.blogspot.com/",
"https://ydc2f65ed.app-ads-txt.com/",
"https://youbia.github.io/",
"https://z241b9ff9.app-ads-txt.com",
"https://z33f953a5.app-ads-txt.com",

]